const products = [
  {
    _id: "1",
    name: "iphone14 256G",
    image: "/images/iphone14.png",
    description: "this is Iphone 14",
    brand: "Apple",
    category: "cellphone",
    price: 999,
    countInStock: 7,
    rating: 4.8,
    numReviews: 5,
  },
  {
    _id: "2",
    name: "iphone14pro 256G",
    image: "/images/iphone14pro.png",
    description: "this is Iphone 14 pro",
    brand: "Apple",
    category: "cellphone",
    price: 1199,
    countInStock: 7,
    rating: 4.8,
    numReviews: 5,
  },
  {
    _id: "3",
    name: "iphone13 128G",
    image: "/images/iphone13_128.png",
    description: "this is Iphone 13 128G",
    brand: "Apple",
    category: "cellphone",
    price: 699,
    countInStock: 7,
    rating: 4.8,
    numReviews: 5,
  },
  {
    _id: "4",
    name: "iphone13 256G",
    image: "/images/iphone13_256.png",
    description: "this is Iphone 13 256G",
    brand: "Apple",
    category: "cellphone",
    price: 799,
    countInStock: 7,
    rating: 3.5,
    numReviews: 5,
  },
  {
    _id: "5",
    name: "iphone13pro 256G",
    image: "/images/iphone13promax.png",
    description: "this is Iphone 13 Pro 256G",
    brand: "Apple",
    category: "cellphone",
    price: 899,
    countInStock: 7,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: "6",
    name: "iphone13promax 256G",
    image: "/images/iphone13promax256.png",
    description: "this is Iphone 13 Pro Max 256G",
    brand: "Apple",
    category: "cellphone",
    price: 999,
    countInStock: 7,
    rating: 4.5,
    numReviews: 5,
  },
];

export default products;
